- hosts: vms
  become: yes
  tasks:
    - name: Install docker | Install required packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: latest
        update_cache: yes

    - name: Install docker | Import docker GPG key
      shell:
        cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        creates: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Install docker | Add docker apt repository
      shell:
        cmd: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          | tee /etc/apt/sources.list.d/docker.list > /dev/null
        creates: /etc/apt/sources.list.d/docker.list

    - name: Install docker | Install docker packages
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
        state: latest
        update_cache: yes

    - name: Install docker | Add user '{{ ansible_user }}' to docker group
      user:
        name: '{{ ansible_user }}'
        groups:
          - docker
        append: yes

    - name: Install docker | Modify daemon.json
      copy:
        dest: /etc/docker/daemon.json
        src: ../files/daemon.json

    - name: Install docker | Enable and start services
      systemd:
        enabled: yes
        state: restarted
        name: docker
